<a href="https://colab.research.google.com/github/Augustine25-git/CDAV/blob/main/MostStreamedArtist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PANDAS

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
counties=pd.Series([4597073,1208333,2162202,1157873])
print(counties)

0    4597073
1    1208333
2    2162202
3    1157873
dtype: int64

In [18]:
df = pd.read_csv('/content/Most Streamed Artists on Spotify (17_07_2026).csv')
df.head()

,Artist,Sex,Country,Langugage,Primary Genre,Artist Type,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
0,Drake,Male,Canada,English,Hip-Hop,Solo,137492.1,94851.1,42640.9,53323.9
1,Taylor Swift,Female,United States,English,Pop,Solo,127861.0,126177.3,1683.8,113421.5
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,125899.8,82189.3,43710.5,48887.0
3,The Weeknd,Male,Canada,English,R&B,Solo,95703.2,77189.4,18513.8,51020.0
4,Justin Bieber,Male,Canada,English,Pop,Solo,78104.4,48316.2,29788.2,29638.3

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Artist                         500 non-null    object
 1   Sex                            500 non-null    object
 2   Country                        500 non-null    object
 3   Langugage                      500 non-null    object
 4   Primary Genre                  500 non-null    object
 5    Artist Type                   500 non-null    object
 6   Total Streams (in millions)    500 non-null    float64
 7   Lead Streams (in millions)     497 non-null    float64
 8   Feature Streams (in millions)  468 non-null    float64
 9   Solo Streams (in millions)     493 non-null    float64
dtypes: float64(4), object(6)
memory usage: 39.2+ KB

In [20]:
df.describe()

,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
count,500.000000,497.000000,468.000000,493.000000
mean,16817.610200,12215.024145,5001.377137,8442.593915
std,14845.197632,11842.628550,6021.629551,9605.072797
min,6972.000000,8.400000,0.400000,1.300000
25%,8768.175000,6568.500000,971.450000,2755.300000
50%,11923.250000,8772.200000,3367.850000,6592.700000
75%,18020.050000,13579.300000,6333.525000,10141.500000
max,137492.100000,126177.300000,43710.500000,113421.500000

In [25]:
df.columns #the coulmn names

Index(['Artist', 'Sex', 'Country', 'Langugage', 'Primary Genre',
       ' Artist Type', 'Total Streams (in millions)',
       'Lead Streams (in millions)', 'Feature Streams (in millions)',
       'Solo Streams (in millions)'],
      dtype='object')

In [22]:
df.dtypes #the type of each column

Artist                            object
Sex                               object
Country                           object
Langugage                         object
Primary Genre                     object
 Artist Type                      object
Total Streams (in millions)      float64
Lead Streams (in millions)       float64
Feature Streams (in millions)    float64
Solo Streams (in millions)       float64
dtype: object

In [23]:
df.index #the row labels

RangeIndex(start=0, stop=500, step=1)

In [24]:
df.size #total number of cells

5000

In [29]:
df['Artist']

0              Drake
1       Taylor Swift
2          Bad Bunny
3         The Weeknd
4      Justin Bieber
           ...
495         The Cure
496       The Marías
497      Limp Bizkit
498             Korn
499      Omar Courtz
Name: Artist, Length: 500, dtype: object

In [30]:
df[['Artist','Primary Genre']]

            Artist Primary Genre
0            Drake       Hip-Hop
1     Taylor Swift           Pop
2        Bad Bunny     Reggaeton
3       The Weeknd           R&B
4    Justin Bieber           Pop
..             ...           ...
495       The Cure          Rock
496     The Marías           Pop
497    Limp Bizkit      Nu Metal
498           Korn         Metal
499    Omar Courtz     Reggaeton

[500 rows x 2 columns]

In [32]:
df.loc[2, 'Artist'] #row labelled 2,column named artist allowing to enter any specific column

'Bad Bunny'

In [34]:
df.iloc[277,0] #third row, first column

'Irshad Kamil'

In [35]:
df.loc[0:3]

,Artist,Sex,Country,Langugage,Primary Genre,Artist Type,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
0,Drake,Male,Canada,English,Hip-Hop,Solo,137492.1,94851.1,42640.9,53323.9
1,Taylor Swift,Female,United States,English,Pop,Solo,127861.0,126177.3,1683.8,113421.5
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,125899.8,82189.3,43710.5,48887.0
3,The Weeknd,Male,Canada,English,R&B,Solo,95703.2,77189.4,18513.8,51020.0

Reading staright from the web

In [ ]:
url=''
df = pd.read_csv(url)
df.head()